name: GitHub Pages Documentation

on:
  push:
    branches:
      - main
    paths:
      - docs/**
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      - name: Restore
        run: dotnet restore
      - name: Build Docs
        run: cd ./docfx && dotnet docfx docfx_project/docfx.json
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docfx/docfx_project/_site
