name: .NET

env:
  GITHUB_USER: Nihlus
  GITHUB_FEED: https://nuget.pkg.github.com/Nihlus
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-restore --no-build --verbosity minimal
    - name: Pack
      run: dotnet pack -c Release --no-restore --no-build --version-suffix "-github$GITHUB_RUN_ID"
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nupkg
        path: nuget/*
  prerelease:
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Download package artifacts
        uses: actions/download-artifact@v3
        with:
          name: nupkg
      - name: Push to GitHub Feed
        run: |
          for f in ./nuget/*; do
            curl -vX PUT -u "$GITHUB_USER:$GITHUB_TOKEN" -F package=@$f $GITHUB_FEED
          done
